version: '1.0.0'
services:
  app:
    restart: unless-stopped
    build: .
    volumes:
      - ./cloud-assignment-2.json:/go/src/app/cloud-assignment-2.json
      - ./internal/res:/go/src/app/internal/res
      - ./template/:/go/src/app/internal/res
    ports:
      - "8000:8080"
